### ISSUE TITLE
Get error when get killed by a mob.

### ISSUE THREAD

**Issue by svenbledt** [stylo019/SkyWall-HardCore-Mode-3.3.5-WoW#2]
lua_scripts/HC/HardcoreMode.lua:3: attempt to call method 'HasItem' (a nil value)

When i get killed by wolfes on human start area it seems it that the item has a nil value wich means player has a nil value i think.

**Comment by stylo019** [comment]
Hi bro,

I will see this, normally its working with "(event, player, killer)".

Thanks for your report :)

**Comment by svenbledt** [comment]
as in #3 

the player here is only removed when someone kills him but not creature because the order in the event is wrong.

https://elunaluaengine.github.io/Global/RegisterPlayerEvent.html

6 / 8  u used wich is a other order.

**Comment by stylo019** [comment]
Yes, thanks for your help. The issue is fixed :)
